hf_token=""
/bin/bash 8TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral lmsys_05 $hf_token
/bin/bash 2DP4TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral lmsys_05 $hf_token
/bin/bash mistral_4DP2TP_fp8.sh alpindale/Mistral-Large-Instruct-2407-FP8 mistral lmsys_05 $hf_token
/bin/bash 8TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral lmsys_025 $hf_token
/bin/bash 2DP4TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral lmsys_025 $hf_token
/bin/bash mistral_4DP2TP_fp8.sh alpindale/Mistral-Large-Instruct-2407-FP8 mistral lmsys_025 $hf_token
/bin/bash 8TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral summarization_05 $hf_token
/bin/bash 2DP4TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral summarization_05 $hf_token
/bin/bash mistral_4DP2TP_fp8.sh alpindale/Mistral-Large-Instruct-2407-FP8 mistral summarization_05 $hf_token
/bin/bash 8TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral summarization_025 $hf_token
/bin/bash 2DP4TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral summarization_025 $hf_token
/bin/bash mistral_4DP2TP_fp8.sh alpindale/Mistral-Large-Instruct-2407-FP8 mistral summarization_025 $hf_token
/bin/bash 8TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral creation_05 $hf_token
/bin/bash 2DP4TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral creation_05 $hf_token
/bin/bash mistral_4DP2TP_fp8.sh alpindale/Mistral-Large-Instruct-2407-FP8 mistral creation_05 $hf_token
/bin/bash 8TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral creation_025 $hf_token
/bin/bash 2DP4TP_fp8.sh mistralai/Mistral-Large-Instruct-2407 mistral creation_025 $hf_token
/bin/bash mistral_4DP2TP_fp8.sh alpindale/Mistral-Large-Instruct-2407-FP8 mistral creation_025 $hf_token
